#!/usr/bin/php
<?php

/* New draft */

$files = array_diff(scandir("."), ["..", "dew", "LICENSE", "html",	
				   ".git", "index.html",
				   "NotoSansArabicUI-Regular.woff2"]);
$new_draft = 1 + intval(max($files));
$timestamp = kurdish_num(time());
$to_write = "سەرناو\t\nڕێکەوت\t{$timestamp}\n\n";
file_put_contents($new_draft, $to_write);
echo "-> $new_draft\n";

/* Functions */

function kurdish_num($str) {
	return str_replace(["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"],
			   ["٠", "١", "٢", "٣", "٤", "٥", "٦", "٧", "٨", "٩"],
			   $str);
}

?>
