#!/usr/bin/php
<?php
$html = "<html dir=rtl>
<head>
<title>ڕەشنووسەکانی ئاڵەکۆک</title>
<meta charset='utf-8'>
<meta name='viewport' content='width=device-width'>
<style>
@font-face {
font-display:swap;
font-family:'nesx';
src:url('//allekok.github.io/src/frontend/style/DroidNaskh-Regular.woff2') format('woff2');
}
body {
margin:.5em;
font-size:1em;
font-family:'nesx';
}
a {
color:#090;
text-decoration:none;
}
header {
margin:2em 1em;
}
header h1 {
font-size:2em;
margin:0;
font-weight:normal;
}
header h1 sup {
font-size:.7em;
}
pre {
white-space:pre-wrap;
word-wrap:break-word;
padding:1em;
margin:.5em auto;
font-size:1em;
font-family:inherit;
line-height:2.5;
border:.7em solid #444;
border-radius:.5em;
max-width:800px;
}
ltr {
direction:ltr;
display:block;
}
.link {
float:left;
font-size:2em;
margin-top:-.5em;
}
</style>
</head>
<body>
<header>
<h1>ڕەشنووسەکانم 
<sup><a href='https://github.com/allekok/drafts'>کۆد</a></sup>
</h1>
</header>";
$output = "index.html";

$inputs = array_diff(scandir("."),
		     [".","..","dew","LICENSE","html",".git","index.html"]);
rsort($inputs);

foreach($inputs as $input) {
	$content = file_get_contents($input);
	$content = htmlspecialchars($content);
	$content = str_replace(["&lt;ltr&gt;", "&lt;/ltr&gt;"],
			       ["<ltr>", "</ltr>"], $content);
	$html .= "<pre id='$input'>";
	$html .= "<a class='link' href='#$input'>#</a>";
	$html .= "$content";
	$html .= "</pre>";
}

$html .= "</body></html>";

file_put_contents($output, $html);

/*
 * Local Variables:
 * mode: web
 * End:
 */
?>
