#!/usr/bin/php
<?php
$html = "<html dir=rtl>
<head>
<title>ڕەشنووسەکانی ئاڵەکۆک</title>
<meta charset='utf-8'>
<meta name='viewport' content='width=device-width'>
<style>
body {
margin:.5em;
font-size:1em;
}
a {
color:#06D;
text-decoration:none;
}
header {

}
header h1 {
font-size:2em;
margin:0;
font-weight:normal;
}
header h1 sup {
font-size:.7em;
}
pre {
white-space:pre-wrap;
word-wrap:break-word;
padding:1em;
margin:.5em 2em .5em 0;
font-size:1.1em;
font-family:auto;
}
pre:nth-child(even) {
border-right:10px solid #06D;
}
pre:nth-child(odd) {
border-left:10px solid #06D;
}
ltr {
direction:ltr;
display:block;
}
</style>
</head>
<body>
<header>
<h1>ڕەشنووسەکانم 
<sup><a href='https://github.com/allekok/drafts'>کۆد</a></sup>
</h1>
</header>";
$output = "index.html";

$inputs = array_diff(scandir("."),
		     [".","..","dew","LICENSE","html",".git","index.html"]);
rsort($inputs);

foreach($inputs as $input) {
	$content = file_get_contents($input);
	$content = htmlspecialchars($content);
	$content = str_replace(["&lt;ltr&gt;", "&lt;/ltr&gt;"],
			       ["<ltr>", "</ltr>"], $content);
	$html .= "<pre>$content</pre>";
}

$html .= "</body></html>";

file_put_contents($output, $html);

/*
 * Local Variables:
 * mode: web
 * End:
 */
?>
